#!/usr/bin/env python3
# sting -- run-in-place launcher for the stinglib package.
#
# Copyright (C) 2026 Uladzislau Bolbas
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# This copy runs sting straight from the source tree: it puts its own
# directory (which contains the stinglib/ package) on sys.path.  The copy
# installed by `make install` instead hard-codes the package directory it
# was installed into; see sting.in and the Makefile.

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))
from stinglib.cli import main

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
